name: Gradle Tasks
on: [ push ]
jobs:
  sanity-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - run: ./gradlew spotlessJavaCheck
    - run: ./gradlew jar
    
