name: Gradle Tasks
on: [ push ]
jobs:
  ci-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Formatting Check
      run: ./gradlew spotlessJavaCheck
    - name: Compile Java Code
      run: ./gradlew assemble
    - name: Unit Tests
      run: mkdir temp && mkdir output && mkdir output/big && mkdir output/joins && mkdir output/indexed && ./gradlew test
    
