name: Gradle Tasks
on: [ push ]
jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
  formatting:
    - run: ./gradlew spotlessJavaCheck
  operator-tests:
    - run: ./gradlew test --tests com.dbms.operators.physical.*
